### PR TITLE
add instructions to README

### PR DESCRIPTION
**Pull request by dsernst**
Adds instructions to highlight some features of this useful tools. 
screen shot 2015-01-11 at 12 42 22 am
Trying to make it a little easier for newcomers to get up to speed.

### CODE REVIEW

**Comment by dsernst** [comment]
:love_letter: bump

**Comment by dsernst** [comment]
😝

**Comment by dglittle** [comment]
sorry I didn't see this! (and thanks!)

**Comment by dsernst** [comment]
All's well that ends well

**Pull request merged**
